#!/bin/sh

if [ ! `which stow` ]; then
    echo Install GNU stow
    echo exit; exit 1
fi;

# Prepare
mkdir -p ~/.vim
mkdir -p ~/.ssh/config.d

# Install
stow -t ~ general
stow -t ~ sources
stow -t ~ tmux
stow -t ~/ -d vim vimrc
stow -t ~/.vim -d vim vim
stow -t ~ zsh
stow -t ~/.ssh ssh
stow -t ~/.local local
