#!/bin/sh

set -ex

if [ ! `which stow` ]; then
    echo Install GNU stow
    echo exit; exit 1
fi;

# Prepare
mkdir -p ~/.vim
mkdir -p ~/.ssh/config.d
mkdir -p ~/.config/nvim
mkdir -p ~/local/bin
mkdir -p ~/.config/kitty
mkdir -p ~/.config/environment.d/

# Install
stow -t ~ \
	-R general \
	-R sources \
	-R tmux \
	-R zsh \
	-R ssh \
	-R vim \
	-R kitty;

# Install vim plugins
vim -c "PlugInstall|qa" 
