export ZSH=/home/rcelha/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(git npm docker docker-compose colorize colored-man-pages yarn nvm)
source $ZSH/oh-my-zsh.sh

for i in ${HOME}/.aliases/*; do
    source $i;
done;

if [ -d ${HOME}/Android ]; then
    export ANDROID_HOME=$HOME/Android/Sdk
    export PATH=$PATH:$ANDROID_HOME/tools
    export PATH=$PATH:$ANDROID_HOME/platform-tools
fi;
