export ZSH=/home/rcelha/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(git npm docker docker-compose colorize colored-man-pages yarn nvm)
source $ZSH/oh-my-zsh.sh

source ${HOME}/.bash_aliases

if [ -f "$NVM_DIR/nvm.sh" ]; then
	autoload -U add-zsh-hook
	load-nvmrc() {
	  local node_version="$(nvm version)"
	  local nvmrc_path="$(nvm_find_nvmrc)"

	  if [ -n "$nvmrc_path" ]; then
		local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

		if [ "$nvmrc_node_version" = "N/A" ]; then
		  nvm install
		elif [ "$nvmrc_node_version" != "$node_version" ]; then
		  nvm use
		fi
	  elif [ "$node_version" != "$(nvm version default)" ]; then
		echo "Reverting to nvm default version"
		nvm use default
	  fi
	}
	add-zsh-hook chpwd load-nvmrc
	load-nvmrc
fi;

[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
