set encoding=utf8

" Code Highlight
set t_Co=256
" set background=dark
syntax enable

" tab as space
set expandtab

" tab size "
set backspace=2
set tabstop=4
set softtabstop=4
set shiftwidth=4

" some tab features
set autoindent
set smarttab

" search
set incsearch "live
set ic "ignoring case
set hlsearch

" showing some info
set number "line number
set title  "title in term
set laststatus=2 "fname in status bar

" editor stuff
set showmatch "show {} and [] open/close tags
" set textwidth=79 "break on 79o caracter
set pastetoggle=<C-v> "copy mode

" multitab
set tabpagemax=15 "15 tabs per instance
map <C-m> <Esc>:tabn<CR>
map <C-n> <Esc>:tabp<CR>
map <C-l> <Esc>:tabs<CR>

set wildmode=list:full
set wildmenu

" Switching themes
let g:mydark_colors = 'CandyPaper'
let g:mylight_colors = 'summerfruit256'
function! s:SwitchTheme()
    if g:colors_name == g:mydark_colors
        execute 'colo ' . g:mylight_colors
    else
        execute 'colo ' . g:mydark_colors
    endif
endfunction
map <silent> <C-c> :call <SID>SwitchTheme()<CR>

" Plug
call plug#begin('~/.vim-plug')

Plug 'rking/ag.vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'vim-airline/vim-airline'

Plug 'plasticboy/vim-markdown', { 'for': 'markdown' }
Plug 'derekwyatt/vim-scala', { 'for': 'scala' }

Plug 'flazz/vim-colorschemes'

let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/]\.(git|hg|svn)|node_modules|__pycache__$',
  \ 'file': '\v\.(exe|so|dll)$',
  \ 'link': 'some_bad_symbolic_links',
  \ }

filetype plugin indent on
call plug#end()

colo CandyPaper
