#!/bin/sh

set -exu

which wget
which curl
which jq

download_url=$(curl https://api.github.com/repos/neovim/neovim/releases/latest | jq -r '.assets[] | select ( .content_type == "application/vnd.appimage") | .browser_download_url')
filename=$(basename $download_url)

cleanup() {
    rm -f $filename
    rm -f ./nvim
}
trap 'cleanup' EXIT

cleanup
wget $download_url
mv $filename nvim
sudo install -b ./nvim /usr/bin
